// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"geulSsi/ent/heart"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HeartCreate is the builder for creating a Heart entity.
type HeartCreate struct {
	config
	mutation *HeartMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (hc *HeartCreate) SetEventID(i int) *HeartCreate {
	hc.mutation.SetEventID(i)
	return hc
}

// SetWriter sets the "writer" field.
func (hc *HeartCreate) SetWriter(s string) *HeartCreate {
	hc.mutation.SetWriter(s)
	return hc
}

// SetIsHeart sets the "is_heart" field.
func (hc *HeartCreate) SetIsHeart(b bool) *HeartCreate {
	hc.mutation.SetIsHeart(b)
	return hc
}

// SetNillableIsHeart sets the "is_heart" field if the given value is not nil.
func (hc *HeartCreate) SetNillableIsHeart(b *bool) *HeartCreate {
	if b != nil {
		hc.SetIsHeart(*b)
	}
	return hc
}

// SetCreatedAt sets the "created_at" field.
func (hc *HeartCreate) SetCreatedAt(t time.Time) *HeartCreate {
	hc.mutation.SetCreatedAt(t)
	return hc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hc *HeartCreate) SetNillableCreatedAt(t *time.Time) *HeartCreate {
	if t != nil {
		hc.SetCreatedAt(*t)
	}
	return hc
}

// Mutation returns the HeartMutation object of the builder.
func (hc *HeartCreate) Mutation() *HeartMutation {
	return hc.mutation
}

// Save creates the Heart in the database.
func (hc *HeartCreate) Save(ctx context.Context) (*Heart, error) {
	hc.defaults()
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HeartCreate) SaveX(ctx context.Context) *Heart {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HeartCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HeartCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HeartCreate) defaults() {
	if _, ok := hc.mutation.IsHeart(); !ok {
		v := heart.DefaultIsHeart
		hc.mutation.SetIsHeart(v)
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		v := heart.DefaultCreatedAt()
		hc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HeartCreate) check() error {
	if _, ok := hc.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Heart.event_id"`)}
	}
	if _, ok := hc.mutation.Writer(); !ok {
		return &ValidationError{Name: "writer", err: errors.New(`ent: missing required field "Heart.writer"`)}
	}
	if _, ok := hc.mutation.IsHeart(); !ok {
		return &ValidationError{Name: "is_heart", err: errors.New(`ent: missing required field "Heart.is_heart"`)}
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Heart.created_at"`)}
	}
	return nil
}

func (hc *HeartCreate) sqlSave(ctx context.Context) (*Heart, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HeartCreate) createSpec() (*Heart, *sqlgraph.CreateSpec) {
	var (
		_node = &Heart{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(heart.Table, sqlgraph.NewFieldSpec(heart.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.EventID(); ok {
		_spec.SetField(heart.FieldEventID, field.TypeInt, value)
		_node.EventID = &value
	}
	if value, ok := hc.mutation.Writer(); ok {
		_spec.SetField(heart.FieldWriter, field.TypeString, value)
		_node.Writer = &value
	}
	if value, ok := hc.mutation.IsHeart(); ok {
		_spec.SetField(heart.FieldIsHeart, field.TypeBool, value)
		_node.IsHeart = value
	}
	if value, ok := hc.mutation.CreatedAt(); ok {
		_spec.SetField(heart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// HeartCreateBulk is the builder for creating many Heart entities in bulk.
type HeartCreateBulk struct {
	config
	err      error
	builders []*HeartCreate
}

// Save creates the Heart entities in the database.
func (hcb *HeartCreateBulk) Save(ctx context.Context) ([]*Heart, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Heart, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HeartCreateBulk) SaveX(ctx context.Context) []*Heart {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HeartCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HeartCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
