// Code generated by ent, DO NOT EDIT.

package heart

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the heart type in the database.
	Label = "heart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldWriter holds the string denoting the writer field in the database.
	FieldWriter = "writer"
	// FieldIsHeart holds the string denoting the is_heart field in the database.
	FieldIsHeart = "is_heart"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the heart in the database.
	Table = "hearts"
)

// Columns holds all SQL columns for heart fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldWriter,
	FieldIsHeart,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsHeart holds the default value on creation for the "is_heart" field.
	DefaultIsHeart bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Heart queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByWriter orders the results by the writer field.
func ByWriter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWriter, opts...).ToFunc()
}

// ByIsHeart orders the results by the is_heart field.
func ByIsHeart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHeart, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
