// Code generated by ent, DO NOT EDIT.

package ent

import (
	"geulSsi/ent/event"
	"geulSsi/ent/heart"
	"geulSsi/ent/schema"
	"geulSsi/ent/user"
	"geulSsi/ent/wisesaying"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[2].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescUpdatedAt is the schema descriptor for updated_at field.
	eventDescUpdatedAt := eventFields[3].Descriptor()
	// event.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	event.DefaultUpdatedAt = eventDescUpdatedAt.Default.(func() time.Time)
	// event.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	event.UpdateDefaultUpdatedAt = eventDescUpdatedAt.UpdateDefault.(func() time.Time)
	heartFields := schema.Heart{}.Fields()
	_ = heartFields
	// heartDescIsHeart is the schema descriptor for is_heart field.
	heartDescIsHeart := heartFields[2].Descriptor()
	// heart.DefaultIsHeart holds the default value on creation for the is_heart field.
	heart.DefaultIsHeart = heartDescIsHeart.Default.(bool)
	// heartDescCreatedAt is the schema descriptor for created_at field.
	heartDescCreatedAt := heartFields[3].Descriptor()
	// heart.DefaultCreatedAt holds the default value on creation for the created_at field.
	heart.DefaultCreatedAt = heartDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	wisesayingFields := schema.WiseSaying{}.Fields()
	_ = wisesayingFields
	// wisesayingDescCreatedAt is the schema descriptor for created_at field.
	wisesayingDescCreatedAt := wisesayingFields[2].Descriptor()
	// wisesaying.DefaultCreatedAt holds the default value on creation for the created_at field.
	wisesaying.DefaultCreatedAt = wisesayingDescCreatedAt.Default.(func() time.Time)
	// wisesayingDescUpdatedAt is the schema descriptor for updated_at field.
	wisesayingDescUpdatedAt := wisesayingFields[3].Descriptor()
	// wisesaying.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wisesaying.DefaultUpdatedAt = wisesayingDescUpdatedAt.Default.(func() time.Time)
	// wisesaying.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wisesaying.UpdateDefaultUpdatedAt = wisesayingDescUpdatedAt.UpdateDefault.(func() time.Time)
}
