// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"geulSsi/ent/predicate"
	"geulSsi/ent/wisesaying"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WiseSayingQuery is the builder for querying WiseSaying entities.
type WiseSayingQuery struct {
	config
	ctx        *QueryContext
	order      []wisesaying.OrderOption
	inters     []Interceptor
	predicates []predicate.WiseSaying
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WiseSayingQuery builder.
func (wsq *WiseSayingQuery) Where(ps ...predicate.WiseSaying) *WiseSayingQuery {
	wsq.predicates = append(wsq.predicates, ps...)
	return wsq
}

// Limit the number of records to be returned by this query.
func (wsq *WiseSayingQuery) Limit(limit int) *WiseSayingQuery {
	wsq.ctx.Limit = &limit
	return wsq
}

// Offset to start from.
func (wsq *WiseSayingQuery) Offset(offset int) *WiseSayingQuery {
	wsq.ctx.Offset = &offset
	return wsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wsq *WiseSayingQuery) Unique(unique bool) *WiseSayingQuery {
	wsq.ctx.Unique = &unique
	return wsq
}

// Order specifies how the records should be ordered.
func (wsq *WiseSayingQuery) Order(o ...wisesaying.OrderOption) *WiseSayingQuery {
	wsq.order = append(wsq.order, o...)
	return wsq
}

// First returns the first WiseSaying entity from the query.
// Returns a *NotFoundError when no WiseSaying was found.
func (wsq *WiseSayingQuery) First(ctx context.Context) (*WiseSaying, error) {
	nodes, err := wsq.Limit(1).All(setContextOp(ctx, wsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wisesaying.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wsq *WiseSayingQuery) FirstX(ctx context.Context) *WiseSaying {
	node, err := wsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WiseSaying ID from the query.
// Returns a *NotFoundError when no WiseSaying ID was found.
func (wsq *WiseSayingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wsq.Limit(1).IDs(setContextOp(ctx, wsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wisesaying.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wsq *WiseSayingQuery) FirstIDX(ctx context.Context) int {
	id, err := wsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WiseSaying entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WiseSaying entity is found.
// Returns a *NotFoundError when no WiseSaying entities are found.
func (wsq *WiseSayingQuery) Only(ctx context.Context) (*WiseSaying, error) {
	nodes, err := wsq.Limit(2).All(setContextOp(ctx, wsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wisesaying.Label}
	default:
		return nil, &NotSingularError{wisesaying.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wsq *WiseSayingQuery) OnlyX(ctx context.Context) *WiseSaying {
	node, err := wsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WiseSaying ID in the query.
// Returns a *NotSingularError when more than one WiseSaying ID is found.
// Returns a *NotFoundError when no entities are found.
func (wsq *WiseSayingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wsq.Limit(2).IDs(setContextOp(ctx, wsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wisesaying.Label}
	default:
		err = &NotSingularError{wisesaying.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wsq *WiseSayingQuery) OnlyIDX(ctx context.Context) int {
	id, err := wsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WiseSayings.
func (wsq *WiseSayingQuery) All(ctx context.Context) ([]*WiseSaying, error) {
	ctx = setContextOp(ctx, wsq.ctx, "All")
	if err := wsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WiseSaying, *WiseSayingQuery]()
	return withInterceptors[[]*WiseSaying](ctx, wsq, qr, wsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wsq *WiseSayingQuery) AllX(ctx context.Context) []*WiseSaying {
	nodes, err := wsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WiseSaying IDs.
func (wsq *WiseSayingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wsq.ctx.Unique == nil && wsq.path != nil {
		wsq.Unique(true)
	}
	ctx = setContextOp(ctx, wsq.ctx, "IDs")
	if err = wsq.Select(wisesaying.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wsq *WiseSayingQuery) IDsX(ctx context.Context) []int {
	ids, err := wsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wsq *WiseSayingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wsq.ctx, "Count")
	if err := wsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wsq, querierCount[*WiseSayingQuery](), wsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wsq *WiseSayingQuery) CountX(ctx context.Context) int {
	count, err := wsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wsq *WiseSayingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wsq.ctx, "Exist")
	switch _, err := wsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wsq *WiseSayingQuery) ExistX(ctx context.Context) bool {
	exist, err := wsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WiseSayingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wsq *WiseSayingQuery) Clone() *WiseSayingQuery {
	if wsq == nil {
		return nil
	}
	return &WiseSayingQuery{
		config:     wsq.config,
		ctx:        wsq.ctx.Clone(),
		order:      append([]wisesaying.OrderOption{}, wsq.order...),
		inters:     append([]Interceptor{}, wsq.inters...),
		predicates: append([]predicate.WiseSaying{}, wsq.predicates...),
		// clone intermediate query.
		sql:  wsq.sql.Clone(),
		path: wsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WiseSaying string `json:"wise_saying,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WiseSaying.Query().
//		GroupBy(wisesaying.FieldWiseSaying).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wsq *WiseSayingQuery) GroupBy(field string, fields ...string) *WiseSayingGroupBy {
	wsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WiseSayingGroupBy{build: wsq}
	grbuild.flds = &wsq.ctx.Fields
	grbuild.label = wisesaying.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WiseSaying string `json:"wise_saying,omitempty"`
//	}
//
//	client.WiseSaying.Query().
//		Select(wisesaying.FieldWiseSaying).
//		Scan(ctx, &v)
func (wsq *WiseSayingQuery) Select(fields ...string) *WiseSayingSelect {
	wsq.ctx.Fields = append(wsq.ctx.Fields, fields...)
	sbuild := &WiseSayingSelect{WiseSayingQuery: wsq}
	sbuild.label = wisesaying.Label
	sbuild.flds, sbuild.scan = &wsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WiseSayingSelect configured with the given aggregations.
func (wsq *WiseSayingQuery) Aggregate(fns ...AggregateFunc) *WiseSayingSelect {
	return wsq.Select().Aggregate(fns...)
}

func (wsq *WiseSayingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wsq); err != nil {
				return err
			}
		}
	}
	for _, f := range wsq.ctx.Fields {
		if !wisesaying.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wsq.path != nil {
		prev, err := wsq.path(ctx)
		if err != nil {
			return err
		}
		wsq.sql = prev
	}
	return nil
}

func (wsq *WiseSayingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WiseSaying, error) {
	var (
		nodes = []*WiseSaying{}
		_spec = wsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WiseSaying).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WiseSaying{config: wsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wsq *WiseSayingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wsq.querySpec()
	_spec.Node.Columns = wsq.ctx.Fields
	if len(wsq.ctx.Fields) > 0 {
		_spec.Unique = wsq.ctx.Unique != nil && *wsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wsq.driver, _spec)
}

func (wsq *WiseSayingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wisesaying.Table, wisesaying.Columns, sqlgraph.NewFieldSpec(wisesaying.FieldID, field.TypeInt))
	_spec.From = wsq.sql
	if unique := wsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wsq.path != nil {
		_spec.Unique = true
	}
	if fields := wsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wisesaying.FieldID)
		for i := range fields {
			if fields[i] != wisesaying.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wsq *WiseSayingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wsq.driver.Dialect())
	t1 := builder.Table(wisesaying.Table)
	columns := wsq.ctx.Fields
	if len(columns) == 0 {
		columns = wisesaying.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wsq.sql != nil {
		selector = wsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wsq.ctx.Unique != nil && *wsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wsq.predicates {
		p(selector)
	}
	for _, p := range wsq.order {
		p(selector)
	}
	if offset := wsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WiseSayingGroupBy is the group-by builder for WiseSaying entities.
type WiseSayingGroupBy struct {
	selector
	build *WiseSayingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wsgb *WiseSayingGroupBy) Aggregate(fns ...AggregateFunc) *WiseSayingGroupBy {
	wsgb.fns = append(wsgb.fns, fns...)
	return wsgb
}

// Scan applies the selector query and scans the result into the given value.
func (wsgb *WiseSayingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wsgb.build.ctx, "GroupBy")
	if err := wsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WiseSayingQuery, *WiseSayingGroupBy](ctx, wsgb.build, wsgb, wsgb.build.inters, v)
}

func (wsgb *WiseSayingGroupBy) sqlScan(ctx context.Context, root *WiseSayingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wsgb.fns))
	for _, fn := range wsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wsgb.flds)+len(wsgb.fns))
		for _, f := range *wsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WiseSayingSelect is the builder for selecting fields of WiseSaying entities.
type WiseSayingSelect struct {
	*WiseSayingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wss *WiseSayingSelect) Aggregate(fns ...AggregateFunc) *WiseSayingSelect {
	wss.fns = append(wss.fns, fns...)
	return wss
}

// Scan applies the selector query and scans the result into the given value.
func (wss *WiseSayingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wss.ctx, "Select")
	if err := wss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WiseSayingQuery, *WiseSayingSelect](ctx, wss.WiseSayingQuery, wss, wss.inters, v)
}

func (wss *WiseSayingSelect) sqlScan(ctx context.Context, root *WiseSayingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wss.fns))
	for _, fn := range wss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
